name: Actualizar últimos videos de YouTube

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Actualizar videos de YouTube
        uses: mohitk05/youtube-readme@main
        with:
          rss_feed: 'https://rss.app/feeds/Dt2dWglUxHLFACrg.xml'
          max_videos: 3
          readme_path: 'README.md'
          start_marker: '<!-- BLOG-POST-LIST:START -->'
          end_marker: '<!-- BLOG-POST-LIST:END -->'
